language:
- cpp

os:
- osx
- linux

compiler:
- clang

before_install:
#- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./ci/linux_before_install.sh; fi
#- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./ci/osx_before_install.sh; fi

# make sure cmake is installed, set up latest GCC C++ compiler if necessary
install:

# - if [ "${TRAVIS_OS_NAME}" = "linux" -a "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script: 
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then scripts/build_gitlab/osx.sh; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then scripts/build_gitlab/linux.sh; fi

