language:
- cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode9.3
    - os: osx
      osx_image: xcode10.3
    - os: osx
      osx_image: xcode11.3

before_install:
#- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./ci/linux_before_install.sh; fi
#- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./ci/osx_before_install.sh; fi

# make sure cmake is installed, set up latest GCC C++ compiler if necessary
install:
#- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt -y install wget libtbb-dev alien; fi
# - if [ "${TRAVIS_OS_NAME}" = "linux" -a "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then scripts/build_gitlab/osx_travis.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then scripts/build_gitlab/linux.sh; fi
