name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake ../scripts/superbuild
    - name: make
      working-directory: build
      run: make -j2
      
  mac-build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake ../scripts/superbuild
    - name: make
      working-directory: build
      run: make -j2
